#**********************************************************
#* CATEGORY    CAMERAS
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright 2020 Haynie IPHC, LLC
#Developed by Haynie Research & Development, LLC
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.#
#You may obtain a copy of the License at
#http://www.apache.org/licenses/LICENSE-2.0
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

- platform: generic
  name: wxradar
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=ICX&brand=wui&num=1&delay=100&type=NTP&frame=0&scale=1&noclutter=0&showstorms=5&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24427697&lat=0&lon=0&label=you%20name:%20RadarGA%20-%20

- platform: ffmpeg
  name: front_porch_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.145/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: back_porch_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.1/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: family_room_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.132/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: living_room_cam
  input: -rtsp_transport udp -i !secret living_room_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: dining_room_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.143/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: kitchen_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.136/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: stairs_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.142/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: upstairs_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.146/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: garage_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.133/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: front_yard_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.1/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: back_yard_cam
  input: -rtsp_transport udp -i rtsp://haynienet:Qz9Zt269J7@10.0.0.105/live
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: driveway_cam
  input: -rtsp_transport udp -i !secret driveway_cam
  extra_arguments: '-vf "scale=384:216"'

